### ISSUE TITLE
Networking ostatnie szlify

### ISSUE THREAD

**Issue by Msaters** [NoosCrim/okrety-delta#15]
Dodac handler (lambda function) w handlowaniu Czytania dla Klienta w celu lepszej uzytkowosci kodu w implementacji klienta
naprzyklad w tym stylu:
```
enum class MessageCode{kon = 0};

class kot{
    std::function<void(MessageCode)> handler = [](MessageCode){};

    void setHandler(const std::function<void(MessageCode)>& _handler)
    {
        handler = _handler;
    }
    //w handlerze Readowania wrzucic   std::function<void(MessageCode)> handler  oraz MessageCode wiadomosci ktora dostalem
};
```

**Comment by Msaters** [comment]
niech server wysle na poczatku graczu (defaultowo) numer 1 ze on zaczyna

**Comment by Msaters** [comment]
?zamienic classe na messanger na namespace?

**Comment by Kamilosok** [comment]
Pozdrawiam

**Comment by Msaters** [comment]
dodac rzeczy zwiazane z inicjalizacja klasy klienta do konstruktora zamiast z zerwnatrz
