### ISSUE TITLE
Konsolidacja modułów

### ISSUE THREAD

**Issue by Kamilosok** [NoosCrim/okrety-delta#24]
Potrzebujemy ostatecznie połączyć moduły **networkingu**, **gry** i **launchera**, jak i również sprawdzić finalnie czy program działa od początku do końca. 
@Msaters 
@TomaszZuranski

**Comment by KamilaKorczynska** [comment]
Launcher odpala bez argumentów wywołania

**Comment by Kamilosok** [comment]
Już działa na manjaro i ubuntu. Czekamy na networking.

**Comment by Msaters** [comment]
Networking wyslany.

**Comment by Kamilosok** [comment]
Ktoś musi przeprowadzić test między dwoma komputerami

**Comment by Kamilosok** [comment]
Test został przeprowadzony, wszystko współgra.
