### ISSUE TITLE
Cross-system compatibility

### ISSUE THREAD

**Issue by Kamilosok** [NoosCrim/okrety-delta#25]
Potrzeba sprawdzić czy wszystko z **launchera** (python) działa na jakimś linuxie, jak i również czy pobranie jedynie biblioteki tkinter jest potrzebne żeby skompilować launcher.
![Bez tytułu](https://github.com/NoosCrim/okrety-delta/assets/80071989/ef053114-6243-40f1-b269-a7eafeac61de)

**Comment by KamilaKorczynska** [comment]
moduł python działa na ubuntu, wystarczy tk

**Comment by NoosCrim** [comment]
> moduł python działa na ubuntu, wystarczy tk

na manjaro tak samo
