### ISSUE TITLE
Dokonczyc Read

### ISSUE THREAD

**Issue by Msaters** [NoosCrim/okrety-delta#29]
Potrzebujemy, żeby w Read me zostały dodane informacje o bibliotekach używanych przy odpalaniu pliku (chyba że nie będzie to potrzebne), ode mnie moge dodać że networking używa asio oraz paru bibliotek standardowych.

**Comment by Kamilosok** [comment]
A wszystkiego już nie ma?

**Comment by NoosCrim** [comment]
wszystko jest poza komendami do kompilacji serwera

**Comment by Kamilosok** [comment]
To je podaj
Skąd mam wiedzieć jak wasze kompilować @Msaters

**Comment by Kamilosok** [comment]
Wszystko ustalone jest w README
